---
# Most of the content in the moduyle is created by the `pdk convert` command.
# This file is where we can define overrides to that static template
Gemfile:
  required:
    ':development':
      - gem: autosign
.gitlab-ci.yml:
  delete: true
.travis.yml:
  includes:
    - env: PUPPET_GEM_VERSION="~> 4.10" CHECK=parallel_spec
      rvm: 2.4.9
      stage: spec  
    -
      env: PUPPET_GEM_VERSION="~> 5.5" CHECK=parallel_spec
      rvm: 2.4.9
      stage: spec  
.vscode/extensions.json:
  unmanaged: false
appveyor.yml:
  delete: true
spec/default_facts.yml:
  extra_facts:
    pe_server_version: null
    pe_logpath: null
    pe_journalpath: null
    pe_configpath: null
    pe_build: null    
